apiVersion: v1
kind: Service
metadata:
  name: forestfires-prediction-service
  labels:
    app: forestfires-prediction
spec:
  selector:
    app: forestfires-prediction
  ports:
    - port: 8080
      targetPort: 8080

